---
- hosts: all
  become: yes
  tasks:
  - name: Echo the Date to a tmp file
    shell: echo  "`date`"> /tmp/date
  - name: Echo String to a tmp file
    shell: echo  "Testing automation in Morpheus" > /tmp/morpheus-test
